#define SET_REGF_Z(x) regs->f_bits.z = (x)
#define GET_REGF_Z() (regs->f_bits.z)
#define SET_REGF_N(x) regs->f_bits.n = (x)
#define GET_REGF_N() (regs->f_bits.n)
#define SET_REGF_H(x) regs->f_bits.h = (x)
#define GET_REGF_H() (regs->f_bits.h)
#define SET_REGF_C(x) regs->f_bits.c = (x)
#define GET_REGF_C() (regs->f_bits.c)